allow-lan: true
dns:
  enable: true
  ipv6: true
  default-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
  use-hosts: true
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
geox-url:
  geoip: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat
  geosite: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb

proxies:
  - {
      'name': 'ğŸ‡­ğŸ‡° ä¸­å›½é¦™æ¸¯ç‰¹åˆ«è¡Œæ”¿åŒº',
      'server': 'data-hk-v1.shwjfkw.cn',
      'port': '20207',
      'type': 'vmess',
      'alterId': '0',
      'cipher': 'auto',
      'network': 'ws',
      'skip-cert-verify': true,
      'tls': false,
      'uuid': 'b1478e24-4916-3abe-8f17-15931012ecbe',
      'ws-opts': { 'headers': { 'Host': 'data-hk-v1.shwjfkw.cn' }, 'path': '/debian' }
    }
  - {
      'name': 'ğŸ‡­ğŸ‡° æ—¥æœ¬',
      'type': 'vmess',
      'server': 'jp01.aikunapp.com',
      'port': '20005',
      'cipher': 'auto',
      'uuid': 'eb6c5021-a13a-4464-ba98-db52f47afaf0',
      'alterId': '0',
      'tls': false,
      'skip-cert-verify': true,
      'network': 'tcp'
    }
  - {
      'name': 'ğŸ‡®ğŸ‡³ å°åº¦',
      'server': '139.59.24.215',
      'port': '3389',
      'type': 'vmess',
      'uuid': '9c050a86-d612-48f1-ec32-e573df08a1b7',
      'alterId': '0',
      'cipher': 'auto',
      'tls': false,
      'skip-cert-verify': true,
      'network': 'http',
      'http-opts': { 'method': 'GET', 'path': ['/'], 'headers': { 'Host': ['internet.life.com.by'] } },
      'udp': true
    }

proxy-groups:
  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - â™»ï¸ å»¶è¿Ÿé€‰ä¼˜
      - ğŸš‘ æ•…éšœè½¬ç§»
      - âš–ï¸ è´Ÿè½½å‡è¡¡(è½®è¯¢)
      - âš–ï¸ è´Ÿè½½å‡è¡¡(æ•£åˆ—)
      - DIRECT
    include-all: true

  - name: â™»ï¸ å»¶è¿Ÿé€‰ä¼˜
    type: url-test
    tolerance: 100
    include-all: true
    lazy: false
    interval: 300
    timeout: 5000
    url: https://www.google.com/gen_204

  - name: ğŸš‘ æ•…éšœè½¬ç§»
    type: fallback
    include-all: true
    lazy: false
    interval: 300
    timeout: 5000
    url: https://www.google.com/gen_204

  - name: âš–ï¸ è´Ÿè½½å‡è¡¡(è½®è¯¢)
    type: load-balance
    strategy: round-robin
    include-all: true
    lazy: false
    interval: 300
    timeout: 5000
    url: https://www.google.com/gen_204

  - name: âš–ï¸ è´Ÿè½½å‡è¡¡(æ•£åˆ—)
    type: load-balance
    strategy: consistent-hashing
    include-all: true
    lazy: false
    interval: 300
    timeout: 5000
    url: https://www.google.com/gen_204

  - name: ğŸŒ å›½å¤–åª’ä½“
    type: select
    proxies: ['ğŸš€ èŠ‚ç‚¹é€‰æ‹©', 'â™»ï¸ å»¶è¿Ÿé€‰ä¼˜', 'ğŸš‘ æ•…éšœè½¬ç§»', 'âš–ï¸ è´Ÿè½½å‡è¡¡(è½®è¯¢)', 'âš–ï¸ è´Ÿè½½å‡è¡¡(æ•£åˆ—)', 'ğŸ¯ å…¨å±€ç›´è¿']
    include-all: true

  - name: ğŸ“² ç”µæŠ¥æ¶ˆæ¯
    type: select
    proxies: ['ğŸš€ èŠ‚ç‚¹é€‰æ‹©', 'â™»ï¸ å»¶è¿Ÿé€‰ä¼˜', 'ğŸš‘ æ•…éšœè½¬ç§»', 'âš–ï¸ è´Ÿè½½å‡è¡¡(è½®è¯¢)', 'âš–ï¸ è´Ÿè½½å‡è¡¡(æ•£åˆ—)', 'ğŸ¯ å…¨å±€ç›´è¿']
    include-all: true

  - name: â“‚ï¸ å¾®è½¯æœåŠ¡
    type: select
    proxies: ['ğŸ¯ å…¨å±€ç›´è¿', 'ğŸš€ èŠ‚ç‚¹é€‰æ‹©', 'â™»ï¸ å»¶è¿Ÿé€‰ä¼˜', 'ğŸš‘ æ•…éšœè½¬ç§»', 'âš–ï¸ è´Ÿè½½å‡è¡¡(è½®è¯¢)', 'âš–ï¸ è´Ÿè½½å‡è¡¡(æ•£åˆ—)']
    include-all: true

  - name: ğŸ è‹¹æœæœåŠ¡
    type: select
    proxies: ['ğŸš€ èŠ‚ç‚¹é€‰æ‹©', 'â™»ï¸ å»¶è¿Ÿé€‰ä¼˜', 'ğŸš‘ æ•…éšœè½¬ç§»', 'âš–ï¸ è´Ÿè½½å‡è¡¡(è½®è¯¢)', 'âš–ï¸ è´Ÿè½½å‡è¡¡(æ•£åˆ—)', 'ğŸ¯ å…¨å±€ç›´è¿']
    include-all: true

  - name: ğŸ“¢ è°·æ­ŒæœåŠ¡
    type: select
    proxies: ['ğŸš€ èŠ‚ç‚¹é€‰æ‹©', 'â™»ï¸ å»¶è¿Ÿé€‰ä¼˜', 'ğŸš‘ æ•…éšœè½¬ç§»', 'âš–ï¸ è´Ÿè½½å‡è¡¡(è½®è¯¢)', 'âš–ï¸ è´Ÿè½½å‡è¡¡(æ•£åˆ—)', 'ğŸ¯ å…¨å±€ç›´è¿']
    include-all: true

  - name: ğŸ¯ å…¨å±€ç›´è¿
    type: select
    proxies: ['DIRECT', 'ğŸš€ èŠ‚ç‚¹é€‰æ‹©', 'â™»ï¸ å»¶è¿Ÿé€‰ä¼˜', 'ğŸš‘ æ•…éšœè½¬ç§»', 'âš–ï¸ è´Ÿè½½å‡è¡¡(è½®è¯¢)', 'âš–ï¸ è´Ÿè½½å‡è¡¡(æ•£åˆ—)']

  - name: ğŸ›‘ å…¨å±€æ‹¦æˆª
    type: select
    proxies: ['REJECT', 'DIRECT']

  - name: ğŸƒ å¹¿å‘Šè¿‡æ»¤
    type: select
    proxies: ['REJECT', 'DIRECT']

  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies: ['ğŸš€ èŠ‚ç‚¹é€‰æ‹©', 'â™»ï¸ å»¶è¿Ÿé€‰ä¼˜', 'ğŸš‘ æ•…éšœè½¬ç§»', 'âš–ï¸ è´Ÿè½½å‡è¡¡(è½®è¯¢)', 'âš–ï¸ è´Ÿè½½å‡è¡¡(æ•£åˆ—)', 'ğŸ¯ å…¨å±€ç›´è¿']
    include-all: true

rule-providers:
  LocalAreaNetwork:
    type: http
    behavior: classical
    format: text
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
    path: ./rulesets/acl4ssr/LocalAreaNetwork.list
    interval: 86400
  UnBan:
    type: http
    behavior: classical
    format: text
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
    path: ./rulesets/acl4ssr/UnBan.list
    interval: 86400
  BanAD:
    type: http
    behavior: classical
    format: text
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
    path: ./rulesets/acl4ssr/BanAD.list
    interval: 86400
  BanProgramAD:
    type: http
    behavior: classical
    format: text
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
    path: ./rulesets/acl4ssr/BanProgramAD.list
    interval: 86400
  GoogleFCM:
    type: http
    behavior: classical
    format: text
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
    path: ./rulesets/acl4ssr/GoogleFCM.list
    interval: 86400
  GoogleCN:
    type: http
    behavior: classical
    format: text
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
    path: ./rulesets/acl4ssr/GoogleCN.list
    interval: 86400
  SteamCN:
    type: http
    behavior: classical
    format: text
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
    path: ./rulesets/acl4ssr/SteamCN.list
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    format: text
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
    path: ./rulesets/acl4ssr/Microsoft.list
    interval: 86400
  Apple:
    type: http
    behavior: classical
    format: text
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
    path: ./rulesets/acl4ssr/Apple.list
    interval: 86400
  Telegram:
    type: http
    behavior: classical
    format: text
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
    path: ./rulesets/acl4ssr/Telegram.list
    interval: 86400
  ProxyMedia:
    type: http
    behavior: classical
    format: text
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
    path: ./rulesets/acl4ssr/ProxyMedia.list
    interval: 86400
  ProxyGFWlist:
    type: http
    behavior: classical
    format: text
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
    path: ./rulesets/acl4ssr/ProxyGFWlist.list
    interval: 86400
  ChinaIp:
    type: http
    behavior: classical
    format: text
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
    path: ./rulesets/acl4ssr/ChinaIp.list
    interval: 86400
  ChinaDomain:
    type: http
    behavior: classical
    format: text
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
    path: ./rulesets/acl4ssr/ChinaDomain.list
    interval: 86400
  ChinaCompanyIp:
    type: http
    behavior: classical
    format: text
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
    path: ./rulesets/acl4ssr/ChinaCompanyIp.list
    interval: 86400
  Download:
    type: http
    behavior: classical
    format: text
    url: https://mirror.ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
    path: ./rulesets/acl4ssr/Download.list
    interval: 86400

rules:
  - RULE-SET,LocalAreaNetwork,ğŸ¯ å…¨å±€ç›´è¿
  - RULE-SET,UnBan,ğŸ¯ å…¨å±€ç›´è¿
  - RULE-SET,BanAD,ğŸ›‘ å…¨å±€æ‹¦æˆª
  - RULE-SET,BanProgramAD,ğŸƒ å¹¿å‘Šè¿‡æ»¤
  - RULE-SET,GoogleFCM,ğŸ“¢ è°·æ­ŒæœåŠ¡
  - RULE-SET,GoogleCN,ğŸ¯ å…¨å±€ç›´è¿
  - RULE-SET,SteamCN,ğŸ¯ å…¨å±€ç›´è¿
  - RULE-SET,Microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡
  - RULE-SET,Apple,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,Telegram,ğŸ“² ç”µæŠ¥æ¶ˆæ¯
  - RULE-SET,ProxyMedia,ğŸŒ å›½å¤–åª’ä½“
  - RULE-SET,ProxyGFWlist,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,ChinaIp,ğŸ¯ å…¨å±€ç›´è¿
  - RULE-SET,ChinaDomain,ğŸ¯ å…¨å±€ç›´è¿
  - RULE-SET,ChinaCompanyIp,ğŸ¯ å…¨å±€ç›´è¿
  - RULE-SET,Download,ğŸ¯ å…¨å±€ç›´è¿
  - GEOIP,LAN,ğŸ¯ å…¨å±€ç›´è¿
  - GEOIP,CN,ğŸ¯ å…¨å±€ç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
